server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_registration_tutorial?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: user-registration_raynermdz
    password: NotUrAvgPassword@#

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          format_sql: true
    show-sql: true